export const planetClickKey = {
  sunClickBox: 'sun',
  mercuryClickBox: 'mercury',
  venusClickBox: 'venus',
  venusShadow: 'venus',
  venusShadowBox: 'venus',
  earthOrbit: 'earth',
  earthShadow: 'earth',
  earthShadowBox: 'earth',
  moonOrbit: 'moon',
  moonShadow: 'moon',
  moonShadowBox: 'moon',
  marsOrbit: 'mars',
  marsShadow: 'mars',
  marsShadowBox: 'mars',
  jupiterOrbit: 'jupiter',
  jupiterShadow: 'jupiter',
  jupiterShadowBox: 'jupiter',
};

export const planetInfoObject = {
  jupiter: {
    name: 'JUPITER',
    diameter: '86,881 Miles',
    orbitalPeriod: '12 Years',
    rotationalPeriod: '10 Hours',
    distanceFromSun: '469.08 Million Miles',
  },
  mars: {
    name: 'MARS',
    diameter: '4,212.3 Miles',
    orbitalPeriod: '687 Days',
    rotationalPeriod: '24.6 Hours',
    distanceFromSun: '155.42 Million Miles',
  },
  earth: {
    name: 'EARTH',
    diameter: '7,917.5 Miles',
    orbitalPeriod: '365 Days',
    rotationalPeriod: '24 Hours',
    distanceFromSun: '94.42 Million Miles',
  },
  moon: {
    name: 'MOON',
    diameter: '2,158.8 Miles',
    orbitalPeriod: '27 Days',
    rotationalPeriod: '27 Days',
    distanceFromSun: null,
    distanceFromEarth: '238,900 Miles',
  },
  venus: {
    name: 'VENUS',
    diameter: '7,520.8 Miles',
    orbitalPeriod: '225 Days',
    rotationalPeriod: '243 Days',
    distanceFromSun: '66.784 Million Miles',
  },
  mercury: {
    name: 'MERCURY',
    diameter: '3,031.9 Miles',
    orbitalPeriod: '88 Days',
    rotationalPeriod: '59 Days',
    distanceFromSun: '43.067 Million Miles',
  },
  sun: {
    name: 'SUN',
    diameter: '865,370 Miles',
    orbitalPeriod: ' 226 Million Years',
    rotationalPeriod: '25 Days',
    distanceFromSun: null,
    distanceFromEarth: '94.42 Million Miles',
  },
};
