export const planetClickKey = {
  sunClickBox: 'sun',
  mercuryClickBox: 'mercury',
  venusClickBox: 'venus',
  venusShadow: 'venus',
  venusShadowBox: 'venus',
  earthOrbit: 'earth',
  earthShadow: 'earth',
  earthShadowBox: 'earth',
  moonOrbit: 'moon',
  moonShadow: 'moon',
  moonShadowBox: 'moon',
  marsOrbit: 'mars',
  marsShadow: 'mars',
  marsShadowBox: 'mars',
  jupiterOrbit: 'jupiter',
  jupiterShadow: 'jupiter',
  jupiterShadowBox: 'jupiter',
};

export const planetInfoObject = {
  jupiter: {
    name: 'JUPITER',
    diameterMetric: '139,820 Kilometers',
    diameterImperial: '86,881 Miles',
    orbitalPeriod: '12 Years',
    rotationalPeriod: '10 Hours',
    distanceFromSunMetric: '752.38 Million Kilometers',
    distanceFromSunImperial: '469.08 Million Miles',
  },
  mars: {
    name: 'MARS',
    diameterMetric: '6,779 Kilometers',
    diameterImperial: '4,212.3 Miles',
    orbitalPeriod: '687 Days',
    rotationalPeriod: '24.6 Hours',
    distanceFromSunMetric: '249.96 Million Kilometers',
    distanceFromSunImperial: '155.42 Million Miles',
  },
  earth: {
    name: 'EARTH',
    diameterMetric: '12,742 Kilometers',
    diameterImperial: '7,917.5 Miles',
    orbitalPeriod: '365 Days',
    rotationalPeriod: '24 Hours',
    distanceFromSunMetric: '149.6 Million Kilometers',
    distanceFromSunImperial: '94.42 Million Miles',
  },
  moon: {
    name: 'MOON',
    diameterMetric: '3,474.8 Kilometers',
    diameterImperial: '2,158.8 Miles',
    orbitalPeriod: '27.3 Days',
    rotationalPeriod: '27.3 Days',
    distanceFromSunMetric: null,
    distanceFromSunImperial: null,
    distanceFromEarthMetric: '384,400 Kilometers',
    distanceFromEarthImperial: '238,900 Miles',
  },
  venus: {
    name: 'VENUS',
    diameterMetric: '12,104 Kilometers',
    diameterImperial: '7,520.8 Miles',
    orbitalPeriod: '225 Days',
    rotationalPeriod: '243 Days',
    distanceFromSunMetric: '108.33 Million Kilometers',
    distanceFromSunImperial: '66.784 Million Miles',
  },
  mercury: {
    name: 'MERCURY',
    diameterMetric: '4,879.4 Kilometers',
    diameterImperial: '3,031.9 Miles',
    orbitalPeriod: '88 Days',
    rotationalPeriod: '59 Days',
    distanceFromSunMetric: '59.196 Million Kilometers',
    distanceFromSunImperial: '43.067 Million Miles',
  },
  sun: {
    name: 'SUN',
    diameterMetric: '1.3972 Million Kilometers',
    diameterImperial: '865,370 Miles',
    orbitalPeriod: ' 226 Million Years',
    rotationalPeriod: '25 Days',
    distanceFromSunMetric: null,
    distanceFromSunImperial: null,
    distanceFromEarthMetric: '149.6 Million Kilometers',
    distanceFromEarthImperial: '94.42 Million Miles',
  },
};
